apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: frontend
  project: default
  source:
    repoURL: ssh://git@github.com/Lorenz-A-Mueller/dummy-frontend.git
    targetRevision: level3
    path: manifests/local
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
